service: juanTorres

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
      Resource:
        - 'arn:aws:dynamodb:us-east-1:*:table/${self:service}-Client'
  
functions:
  client:
    handler: client.handler
    name: ${self:service}-${self:provider.stage}-create-client
    events:
      - http:
          method: post
          path: create/client
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
          - "sqs:GetQueueUrl"
        Resource: 
          - !GetAtt CardQueue.Arn
          - !GetAtt GiftQueue.Arn
    environment:
      SQSURLCARD: { Ref : CardQueue}
      SQSURLGIFT: { Ref : GiftQueue}
  card:
    handler: card.handler
    name: ${self:service}-${self:provider.stage}-create-card
    events:
      - sqs:
          arn: !GetAtt CardQueue.Arn
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:ReceiveMessage"
        Resource: !GetAtt CardQueue.Arn
  
  gift:
    handler: gift.handler
    name: ${self:service}-${self:provider.stage}-create-gift
    events:
      - sqs:
          arn: !GetAtt GiftQueue.Arn
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:ReceiveMessage"
        Resource: 
          - !GetAtt GiftQueue.Arn

resources:
  Resources:
    CardQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-cardqueue
    CardQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        PolicyDocument: 
          Statement:
            - Effect: Allow
              Action: 
                - SQS:*
              Resource: !GetAtt CardQueue.Arn
              Principal:
                AWS:
                  - !Ref AWS::AccountId
            - Effect: Allow
              Principal:
                AWS: 
                  - '*'
              Action: 
                - SQS:SendMessage
              Resource: !GetAtt CardQueue.Arn
        Queues: 
          - !Ref CardQueue
    
    GiftQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-giftqueue
    GiftQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        PolicyDocument: 
          Statement:
            - Effect: Allow
              Action: 
                - SQS:*
              Resource: !GetAtt GiftQueue.Arn
              Principal:
                AWS:
                  - !Ref AWS::AccountId
            - Effect: Allow
              Principal:
                AWS: 
                  - '*'
              Action: 
                - SQS:SendMessage
              Resource: !GetAtt GiftQueue.Arn
        Queues: 
          - !Ref GiftQueue